insert into Participante(id,nome,email,torcedor_time) values(null,'André Oliveira','andre.stoliver@gmail.com','NO');
insert into Participante(id,nome,email,torcedor_time) values(null,'Carlos Augusto Danety','carlos@onety.com.br','PHI');
insert into Participante(id,nome,email,torcedor_time) values(null,'Cesar Augusto de Freitas','cesarfreitas94@yahoo.com.br','GB');
insert into Participante(id,nome,email,torcedor_time) values(null,'David Geber','david.gebertkd@yahoo.com.br','GB');
insert into Participante(id,nome,email,torcedor_time) values(null,'Edgar Carreiro Jr','edgarpib@gmail.com','NE');
insert into Participante(id,nome,email,torcedor_time) values(null,'Eduardo Vieira','evieira@infolink.com.br','SF');
insert into Participante(id,nome,email,torcedor_time) values(null,'Evandro Ramos','vandro_0@outlook.com','NE');
insert into Participante(id,nome,email,torcedor_time) values(null,'Fabricio Barbosa','fabriciouerj@gmail.com','BAL');
insert into Participante(id,nome,email,torcedor_time) values(null,'Fabricio Bonzi','fabriciobonzi@gmail.com','ARI');
insert into Participante(id,nome,email,torcedor_time) values(null,'Filipe Farias','fffarias@gmail.com','DAL');
insert into Participante(id,nome,email,torcedor_time) values(null,'Guilerme Mendes','guilherme_gmc@hotmail.com','PIT');
insert into Participante(id,nome,email,torcedor_time) values(null,'Guilherme Puppim','guitec09@gmail.com','OAK');
insert into Participante(id,nome,email,torcedor_time) values(null,'Guilherme Pazzetti','guilhermepazzetti@hotmail.com','GB');
insert into Participante(id,nome,email,torcedor_time) values(null,'Helio Paiva','helio.paiva@itamaraty.gov.br','WAS');
insert into Participante(id,nome,email,torcedor_time) values(null,'Igor Thurler','igorthurler@fumblecast.com.br','DEN');
insert into Participante(id,nome,email,torcedor_time) values(null,'Israel Schneid','israelschneid@gmail.com','GB');
insert into Participante(id,nome,email,torcedor_time) values(null,'Jailson Carvalho','jonhbrt@gmail.com','SF');
insert into Participante(id,nome,email,torcedor_time) values(null,'Jonas Fernandez','jonas@fumblecast.com.br','GB');
insert into Participante(id,nome,email,torcedor_time) values(null,'Larissa Teixeira','lteixeirabento@gmail.com','NE');
insert into Participante(id,nome,email,torcedor_time) values(null,'Leandro Martins','martinsrpv@gmail.com','NE');
insert into Participante(id,nome,email,torcedor_time) values(null,'Leonardo Rocha','leorocha920@hotmail.com','NYG');
insert into Participante(id,nome,email,torcedor_time) values(null,'Leandro Zepechouka','leandro-zep@live.com','NYG');
insert into Participante(id,nome,email,torcedor_time) values(null,'Marcos junio Costa lino','marcosjunio_dpm@hotmail.com','DEN');
insert into Participante(id,nome,email,torcedor_time) values(null,'Mário Antônio Magalhães Côgo','marioamcogo@gmail.com','NO');
insert into Participante(id,nome,email,torcedor_time) values(null,'Marlon Espindola','marlonespindola@gmail.com','GB');
insert into Participante(id,nome,email,torcedor_time) values(null,'Michael Jackson','Michael.Moreira@live.com','PHI');
insert into Participante(id,nome,email,torcedor_time) values(null,'Rafael B2','rafaelbarros@fumblecast.com.br','WAS');
insert into Participante(id,nome,email,torcedor_time) values(null,'Rafa Nogueira','rafael.nogueira@fumblecast.com.br','IND');
insert into Participante(id,nome,email,torcedor_time) values(null,'Rafael Lisboa','rafael.lisboa0@gmail.com','JAX');
insert into Participante(id,nome,email,torcedor_time) values(null,'Rodrigo Rosa','rr0082@gmail.com','SF');
insert into Participante(id,nome,email,torcedor_time) values(null,'Ryed Jones','ryedjhonesp@gmail.com','DAL');
insert into Participante(id,nome,email,torcedor_time) values(null,'Thiago Murta','thiagom49ers@gmail.com','SF');
insert into Participante(id,nome,email,torcedor_time) values(null,'Tierry','rhighlanders@gmail.com','NE');
insert into Participante(id,nome,email,torcedor_time) values(null,'Willian Anjos','zocrof@icloud.com','NE');
insert into Participante(id,nome,email,torcedor_time) values(null,'Yordan Gums','yordan_gums@yahoo.com','SF');